"use client";

// import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "next-frontend-starter",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();
  return (
    <html lang="en">
      <body className="bg-blue-100">
        <Toaster position="bottom-right" toastOptions={{ duration: 5000 }} />
        { path !== "/" && (<header className="flex items-center justify-center h-10 bg-indigo-400 w-50 rounded-xl">
              <Link className="text-white hover:text-black relative" href={"/"}>Vissza a főmenübe</Link>
        </header>)}
        {children}
      </body>
    </html>
  );
}